name: tests-cli

on:
  push:

jobs:
  tests-cli:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 18, 20, 22, 24 ]

    steps:
    - name: checkout
      uses: actions/checkout@v5

    - name: setup node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node }}

    - run: npm ci

    - run: npm link
    
    - run: markdown

    - run: markdown tests/sample.md
